menu:
- {name: 'solution', url: '/solution'}
- {name: 'outreach', url: '/outreach'}
- {name: 'analytics', url: '/analytics'}

social:
- {icon: 'github', link: 'https://github.com/anaypant'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/anay-pant/'}

contacts:
- {name: 'Anay Pant', title: 'Student at The Athenian School'}
