menu:
- {name: 'research', url: '/research'}
- {name: 'userstudy', url: '/userstudy'}
- {name: 'about', url: '/about'}

social:
- {icon: 'github', link: 'https://github.com/anaypant'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/anay-pant/'}

contacts:
- {name: 'Anay Pant', title: 'Student at The Athenian School'}
